######################################################################
# Automatically generated by qmake (2.01a) vie mar 28 13:01:47 2008
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
