######################################################################
# Automatically generated by qmake (2.01a) mi� mar 26 21:37:48 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qtestlib

# Input
SOURCES += main.cpp
