######################################################################
# Automatically generated by qmake (2.01a) vie mar 28 12:00:25 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qtestlib

# Input
SOURCES += main.cpp
